### PR TITLE
fix: Fail with a specific error when unauthenticated

### LINKED ISSUE #792: no gitlab projects found from remotes
**Description**
Getting the error "no gitlab projects found from remotes" when running glab issue list
`glab auth status` returns all green check marks
**Expected Behavior vs Actual Behavior**
List the issues

**Steps to Reproduce**
$ glab auth login --stdin < token.txt
$ glab issue list

**Your Environment**
glab version 1.18
gitlab version 14.01

### LINKED ISSUE #877: Can't get glab to work in repo
**Description**
I started to experiment around with glab, but somehow i can't get past the repo clone:

``` shell
~ # glab auth login -h ${GITLAB_HOST} -t ${GITLAB_TOKEN}
~ # glab repo clone "https://${GITLAB_HOST}/EDV/dokumentation"
Cloning into 'dokumentation'...
remote: Enumerating objects: 902, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 902 (delta 5), reused 10 (delta 3), pack-reused 887
Receiving objects: 100% (902/902), 1.97 MiB | 10.23 MiB/s, done.
Resolving deltas: 100% (518/518), done.
~ # cd dokumentation/
~/dokumentation # glab issue list
no GitLab Projects found from remotes
```

am i doing something wronge? I searched the whole documentation but could not find a hint about what to do here!

### PR DESCRIPTION
**Pull request by carlpett**
If resolutions fails, return the error instead of "no GitLab Projects found from remotes"

## Description
Currently, a misleading/confusing error is returned if authentication fails. This PR changes it to return the actual error instead.

## Related Issue

_Possibly_ resolves #792
_Possibly_ resolves #877

## How Has This Been Tested?
Tested with bad token, added some test cases

## Screenshots (if appropriate)
-

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by carlpett** [comment]
@profclems Anything I need to do to get this reviewed, or just a question of finding time on your end? The DeepSource thing does not look related to my changes, unsure what to do about it.

**Review by zemzale — COMMENTED** [review]
This change would likely break network resolving for someone. 

The current implementation loops over the remotes(max number of 5) and adds them to the networks list, if there is no error.

The new implementation would fail with the first error(which could be any not 200 OK response from GitLab), meaning it would not try to connect to all possible remotes.

The idea to add more context to the error is good, but the implementation needs something more. 
I imagine maybe saving the errors into a slice, and if no remotes got found, then create one big error that gets passed down the stack with all the context?

@profclems some extra info would be great here, since I have not deep dived into the interlans of the network resolver.

**Comment by carlpett** [comment]
So, a `network` is a remote? I think I was a bit confused on what it was meant to represent.
Would the correct behaviour be to succeed if _any_ remote returns successfully?

**Comment by zemzale** [comment]
I am gonna be honest, but those namings confuse me, but yeah the correct behavior would be to succeed if any remote returns successfully. 

This whole code path basically is our way of trying to find out to which remotes for this project might be available.

**Comment by profclems** [comment]
Hi @carlpett, @zemzale is right. This change will break network resolution for repositories with multiple authenticated remotes. 

The idea behind the network resolution is to find the remote that is authenticated among the available remotes. This will fail if any of the remotes is unreachable. 

Maybe we can group the errors and print them out when the resolution fails just like @zemzale said.

File: internal/glrepo/resolver.go [hunk 1]
```diff
@@ -37,14 +37,17 @@ func ResolveRemotesToRepos(remotes Remotes, client *gitlab.Client, base string)
...
 }
 
-func resolveNetwork(result *ResolvedRemotes) {
+func resolveNetwork(result *ResolvedRemotes) error {
 	// Loop over at most 5 (maxRemotesForLookup)
 	for i := 0; i < len(result.remotes) && i < maxRemotesForLookup; i++ {
 		networkResult, err := api.GetProject(result.apiClient, result.remotes[i].FullName())
 		if err == nil {
 			result.network = append(result.network, *networkResult)
+		} else {
```
Comment (profclems) [inline internal/glrepo/resolver.go:51]: Seems like we are taking the fail fast approach and this will fail network resolution if the first remote is not reachable. 

See my comment here: https://github.com/profclems/glab/pull/886#issuecomment-959662401

**Review by profclems — CHANGES_REQUESTED** [review]

**Comment by carlpett** [comment]
I've pushed an updated version now, which only fails if all remotes fail. I opted to use hashicorp/go-multierror to do error aggregation since it was already an indirect dependency. Let me know if you have other preferences!

**Review by zemzale — APPROVED** [review]
This LGTM. If @profclems doesn't have any more comments I think this should be merged.

**Review by profclems — CHANGES_REQUESTED** [review]
I think you need to run `go mod tidy` on this change

**Comment by carlpett** [comment]
Ouch, missed the last comment, sorry!
Pushed a tidy

**Review by profclems — APPROVED** [review]
