### PR TITLE
fix(mr): Readd ability to close multiple MRs

### LINKED ISSUE #301: [Bug] `mr close` panics with index out of range [0] with length 0
`glab mr close` panics when merge request ID is not provided.

**Expected Behaviour**

If the merge request id is not provided, `glab` should find the open merge request for the current checked out branch and close it

**Actual Behaviour**
```sh
→ glab mr close
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/profclems/glab/commands/mr/close.NewCmdClose.func1(0xc0002e8580, 0x14a4e48, 0x0, 0x0, 0x0, 0x0)
        github.com/profclems/glab/commands/mr/close/mr_close.go:43 +0x605
github.com/spf13/cobra.(*Command).execute(0xc0002e8580, 0x14a4e48, 0x0, 0x0, 0xc0002e8580, 0x14a4e48)
        github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000405080, 0xc000102160, 0x2, 0x2)
        github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
main.main()
        github.com/profclems/glab/cmd/glab/main.go:114 +0x736
```

It works when merge request ID is provided
```sh
→ glab mr close 359
- Closing Merge request...✔ Merge request !359
!359 fix: error 500 when creating purchase order' (fix-err-500-purchase-order)
 https://gitlab.com/ssisgh-projects/simeds/back-end/-/merge_requests/359
```

### PR DESCRIPTION
**Pull request by zemzale**
**Description**
Ability to remove multiple MRs was there but it had gone missing when
implementing `MRFromArgs`.

Added a function for concurrently fetching multiple merge requests from
branches that, falsback to the `MRFromArgs` if the argument count is
lower then 1. This is because the MRFromArgs, contains some specific
logic for handling cases where there are no arguments or user provided
0 in arguments.

Added this functionality to deal with more then one MR to `delete` and `reopen`. 
I opted to not implement this functionality to `merge` command since, if there merge multiple MRs one might create merge conflicts to others and block the merging.  

**Related Issue**
Fixes #301

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: commands/mr/mrutils/mrutils.go [hunk 1]
```diff
@@ -151,6 +153,54 @@ func MRFromArgs(f *cmdutils.Factory, args []string) (*gitlab.MergeRequest, glrep
 	return mr, baseRepo, nil
 }
 
+func MRsFromArgs(f *cmdutils.Factory, args []string) ([]*gitlab.MergeRequest, glrepo.Interface, error) {
+	if len(args) <= 1 {
```
Comment (profclems) [inline commands/mr/mrutils/mrutils.go:158]: There is a restriction on the `mr close` command on this line indicating it cannot have more than one positional arguments:
https://github.com/profclems/glab/blob/9b0868068e88acdec171aa07d6651df537b72986/commands/mr/close/mr_close.go#L21

I'm glad you did it this way so we can have room for cases where we allow multiple positional arguments (`glab mr close 1 2 3 4`) but for backward compatibility where the user can do `glab mr close 1,2,3,4` to close multiple MRs , you should check for when there is a single argument with comma-separated IDs.

```go
if len(args) <= 1 {
        var arrIds []string
        if(len(args) == 1) {
	        arrIds := strings.Split(mergeID, ",")
        }
        if (len(arrids) <= 1) {
		mrID, baseRepo, err := MRFromArgs(f, args)
		if err != nil {
			return nil, nil, err
		}
		return []*gitlab.MergeRequest{mrID}, baseRepo, err
	}
        args = arrIds
}
```

Comment (zemzale) [reply commands/mr/mrutils/mrutils.go:158]: I didn't think of the backwards compatibility with comma separated arguments. 
In this MR I ended up removing the constrain to the maximum arguments, but the correct thing would be to just revert back to the single argument and have it comma separated, and do it this way.

Comment (zemzale) [reply commands/mr/mrutils/mrutils.go:158]: Off-topic: Do you mind that I force push to my PRs? 
I know some people don't like when someone does that because they like to go through PRs commit by commit, but I like to have my commits tidy, and if I make a mistake in a commit I ammend to it and force push it, like the mistake never existed.

Comment (profclems) [reply commands/mr/mrutils/mrutils.go:158]: That's okay

**Review by profclems — APPROVED** [review]

File: commands/mr/mrutils/mrutils.go (hunk 1 above)
Comment (profclems) [reply commands/mr/mrutils/mrutils.go:158]: You can merge this PR now. I have reviewed and approved
