### PR TITLE
Retry work

### LINKED ISSUE #719: segfault when trying to rebase&&merge
**Description**

Segfault on `retry.Do` function, when merging a merge request that needs to be rebased.

after the segfault if it is asked to merge again then it will work normally

**Expected Behavior vs Actual Behavior**

that it is merged instead of segfault

**Steps to Reproduce**

1. Find a merge request that needs to be rebased
2. run `gllab mr merge --yes --rebase --when-pipeline-succeeds=false <MR-IDENTIFIER>`
3. See error

**Logs**

```
✓ Rebase successful
| Merging merge request !21321 panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbdb797]

goroutine 1 [running]:
github.com/profclems/glab/commands/mr/merge.NewCmdMerge.func1.1(0xc0008d1aa8, 0xc0008d1a78)
	github.com/profclems/glab/commands/mr/merge/mr_merge.go:187 +0xb7
github.com/avast/retry-go.Do(0xc0008d1c50, 0x0, 0x0, 0x0, 0x1, 0x1)
	github.com/avast/retry-go@v3.0.0+incompatible/retry.go:127 +0x1cc
github.com/profclems/glab/commands/mr/merge.NewCmdMerge.func1(0xc000580280, 0xc0000ccc40, 0x1, 0x4, 0x0, 0x0)
	github.com/profclems/glab/commands/mr/merge/mr_merge.go:184 +0x6ad
github.com/spf13/cobra.(*Command).execute(0xc000580280, 0xc0000ccc00, 0x4, 0x4, 0xc000580280, 0xc0000ccc00)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a8f00, 0xc00000e018, 0x7a, 0x6)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
main.main()
	github.com/profclems/glab/cmd/glab/main.go:140 +0x7d7
```
**Your Environment**

* Version used (Run `glab --version`): glab version 1.16.0-66-g649df1c (2021-05-12)
* Operating System and version: Fedora Silverblue 34

### PR DESCRIPTION
**Pull request by maxice8**
**Description**

This function uses the `retry.Options` as documented in the system and fixes a segfault

**Related Issue**

Resolves #719 

**How Has This Been Tested?**

Merged stuff on `gitlab.alpinelinux.org`

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation
- [ ] Chore (Related to CI or Packaging to platforms)

### CODE REVIEW

**Comment by maxice8** [comment]
we might want to use `RetryIf` and abort if the error isn't the one we expected, this would make us exit earlier if the error is not  the one we are working around

**Comment by maxice8** [comment]
From https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr

```txt
If it has some conflicts and can not be merged - you receive a 406 and the error message ‘Branch cannot be merged’
```

**Comment by maxice8** [comment]
Reworked to have `api.MergeMR` return the `*gitlab.Response`, we need to verify the status code we have to be `406`

File: commands/mr/merge/mr_merge.go [hunk 1]
```diff
@@ -187,8 +187,18 @@ func NewCmdMerge(f *cmdutils.Factory) *cobra.Command {
...
+				mr, resp, err = api.MergeMR(apiClient, repo.FullName(), mrIID, mergeOpts)
+				if err != nil {
+					// https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr
+					// `406` is the documented status code we will receive if the
+					// branch cannot be merged, also make sure we are rebasing
+					// before we merge as this is the specific situation we are
+					// avoiding
+					if opts.RebaseBeforeMerge && resp.StatusCode == 406 {
+						return err
+					}
```
Comment (profclems) [inline commands/mr/merge/mr_merge.go]: It will be best to check for only the status code. The user might have already initiated a rebase either on the web UI or used `glab mr rebase` before running `glab mr merge` without using the `--rebase` flag so a rebase could be in progress

```suggestion
					if resp.StatusCode == 406 {
						return err
					}
```

**Review by profclems — CHANGES_REQUESTED** [review]
Good work @maxice8... Thanks a lot

File: commands/mr/merge/mr_merge.go (hunk 1 above)
Comment (maxice8) [reply commands/mr/merge/mr_merge.go]: Thanks, I didn't consider that the user can do a rebase via an external source before.

**Review by profclems — APPROVED** [review]
